apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeops.fullname" . }}-secret
  labels:
    {{- include "kubeops.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded values
  database-url: cG9zdGdyZXNxbDovL2t1YmVvcHM6a3ViZW9wc0AvcG9zdGdyZXNxbD9zcGxpbWV0aW1lczw9am9pbl9zZXJ2aWNl
  openai-api-key: {{ .Values.config.ai.openai.apiKey | b64enc | default "" }}
  jenkins-password: {{ .Values.config.devops.jenkins.password | b64enc | default "" }}
  argocd-token: {{ .Values.config.devops.argocd.authToken | b64enc | default "" }}
